# Generated by Django 2.2.6 on 2020-11-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Name', models.CharField(default=0, max_length=20)),
                ('Image', models.BinaryField(blank=True)),
                ('phone_no', models.CharField(default=0, max_length=20)),
                ('address', models.CharField(default='null', max_length=200)),
            ],
        ),
    ]
